/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/**/*.{js/jsx/ts/tsx}"],
  theme: {
    extend: {
      fontFamily: {
        arial: ["Arial", "cursive"],
        helvetica: [" Helvetica", "cursive"],
        opensans: ["OpenSans", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        simsun: ["Simsun", "cursive"],
        raleway: ["Raleway", "cursive"],
      },
      backgroundColor: {
        bgcolor: "#f2f2f2",
        bgLemonBlueDark: "#2e9cc3",
        bgLemonBlueLight: "#b0e9ff",
        bgDarkRed: "#ff4747",
        bgBlueDark: "#b9c5d6",
      },
      colors: {
        deepGray: "#3a3e4a",
        darkRed: "#ff4747",
        goldDeep: "#D4AF37",
      },
      fontSize: {
        main: ["14px", "10px"],
        xss: ["12px", "10px"],
        md: ["16px", "22px"],
      },
      width: {
        one: "10%",
        two: "20%",
        three: "30%",
        four: "40%",
        five: "50%",
        six: "60%",
        seven: "70%",
        eight: "80%",
        nine: "90%",
      },
      maxWidth: {
        one: "10%",
        two: "20%",
        three: "30%",
        four: "40%",
        five: "50%",
        six: "60%",
        seven: "70%",
        eight: "80%",
        nine: "90%",
      },
      minWidth: {
        one: "10%",
        two: "20%",
        three: "30%",
        four: "40%",
        five: "50%",
        six: "60%",
        seven: "70%",
        eight: "80%",
        nine: "90%",
      },
      maxHeight: {
        one: "10%",
        two: "20%",
        three: "30%",
        four: "40%",
        five: "50%",
        six: "60%",
        seven: "70%",
        eight: "80%",
        nine: "90%",
      },
      minHeight: {
        one: "10%",
        two: "20%",
        three: "30%",
        four: "40%",
        five: "50%",
        six: "60%",
        seven: "70%",
        eight: "80%",
        nine: "90%",
      },
      height: {
        one: "10%",
        two: "20%",
        three: "30%",
        four: "40%",
        five: "50%",
        six: "60%",
        seven: "70%",
        eight: "80%",
        nine: "90%",
      },
      inset: {
        r: "right-0",
      },
      keyframes: {
        "slide-animate": {
          "0%": {
            "-moz-transform": "translateX(0%)",
            transform: "translateX(0%)",
            "-webkit-transform": "translateX(0%)",
          },
          "100%": {
            "-moz-transform": "translateX(-100%)",
            transform: "translateX(-100%)",
            "-webkit-transform": "translateX(-100%)",
          },
        },
      },
      animation: {
        "slide-animate": "slide-animate 15s linear infinite alternate",
      },
    },
  },
  plugins: [
    require("@tailwindcss/line-clamp"),
    require("tailwind-scrollbar")({ nocompatible: true }),
  ],
};
